### ISSUE TITLE
[1월 25일~ 1월 31일] 김진영 TODO

### ISSUE THREAD

**Issue by jy-kkkim** [Gachon-P-project/Back#22]
## 주요 내용
- [ ] AWS 보안 업데이트
- [ ] 테스트 서버 Docker + Jenkins 배포
- [x] 학과 코드 DB화
- [x] 로그인 로직 수정
- [x] 상용 서버 트러블 슈팅

## 상세 내용
1. AWS 보안 업데이트
    - 무차별 공격 대응

2. 테스트 서버 Docker + Jenkins 배포
    - 배포 자동화

3. 학과 코드 DB화
    - 로그인 로직 수정을 위한 학과 코드 DB화
    - 노가다 작업..

4. 로그인 로직 수정
    - clubName이 빈 객체로 전달되는 계정의 로그인 오류 해결을 위한 로직 수정
    - 학과 코드 이용

## 특이사항
AWS 요금이 생각보다 너무 안나오는군요

**Comment by jy-kkkim** [comment]
로그인 로직 실패
