### ISSUE TITLE
[2월 8일~ 2월 14일] 박상도 TODO

### ISSUE THREAD

**Issue by bansakdo** [Gachon-P-project/Back#31]
## 주요 내용
- [ ] 개별 홈페이지 사용하는 학과 공지사항 크롤링 #15
   - [x]  해당 학과 학생들에게 맞는 공지사항 데이터 제공
   - [ ]  공지사항 새 글 크롤링 할 때(푸시 알림) 이 학과들도 포함
## 상세 내용
1. 개별 홈페이지 사용하는 학과 공지사항 크롤링 #15
    - 해당 학과 학생들에게 맞는 공지사항 데이터 제공
    - 공지사항 새 글 크롤링 할 때(푸시 알림) 이 학과들도 포함
    
## 특이사항
내용입력
